export const formControls = [
	{
		name        : 'name',
		label       : 'Name',
		type        : 'text',
		placeholder : '',
		rules       : { required: true },
	},
	{
		name        : 'imo',
		label       : 'IMO',
		type        : 'text',
		placeholder : '',
		rules       : { required: true },
	},
	{
		name        : 'owner_name',
		label       : 'Owner Name',
		type        : 'text',
		placeholder : '',
		rules       : {},
	},
	{
		name        : 'owner_line_id',
		label       : 'Owner Line',
		type        : '',
		placeholder : '',
		rules       : {},
	},
	{
		name        : 'previous_owners',
		label       : 'Previous Owners',
		type        : 'fieldArray',
		rules       : {},
		emptyValues : {
			owner_name    : '',
			owner_line_id : '',
		},
		controls: [
			{
				name        : 'owner_line_id',
				label       : 'Owner Line',
				type        : 'async_select',
				placeholder : '',
				rules       : {},
			},
			{
				name  : 'customUI',
				label : 'OR',
			},
			{
				name        : 'owner_name',
				label       : 'Owner Name',
				type        : 'text',
				placeholder : '',
				rules       : { },
			},
		],
	},
	{
		name        : 'meta_data',
		label       : 'Meta Data',
		type        : 'fieldArray',
		placeholder : '',
		rules       : {},
		emptyValues : {
			source       : '',
			callsign     : '',
			eni          : '',
			mmsi         : '',
			country      : '',
			countryCode  : '',
			grossTonnage : '',
			deadweight   : '',
			teu          : '',
			length       : '',
			breadth      : '',
			yearBuilt    : '',
			type         : '',
		},
		controls: [
			{
				name        : 'source',
				label       : 'Source',
				type        : 'text',
				placeholder : 'website link',
				rules       : {},
			},
			{
				name        : 'callsign',
				label       : 'Call Sign',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
			{
				name        : 'eni',
				label       : 'ENI',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
			{
				name        : 'mmsi',
				label       : 'MMSI',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
			{
				name        : 'country',
				label       : 'Country',
				type        : 'text',
				placeholder : '',
				rules       : { required: true },
			},
			{
				name        : 'countryCode',
				label       : 'Country Code',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
			{
				name        : 'grossTonnage',
				label       : 'Gross Tonnage',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
			{
				name        : 'deadweight',
				label       : 'Dead Weight',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
			{
				name        : 'teu',
				label       : 'TEU',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
			{
				name        : 'length',
				label       : 'Length',
				type        : 'text',
				placeholder : '',
				rules       : { required: true },
			},
			{
				name        : 'breadth',
				label       : 'Breadth',
				type        : 'text',
				placeholder : '',
				rules       : { required: true },
			},
			{
				name        : 'yearBuilt',
				label       : 'Year Built',
				type        : 'text',
				placeholder : '',
				rules       : { required: true },
			},
			{
				name        : 'type',
				label       : 'Type',
				type        : 'text',
				placeholder : '',
				rules       : {},
			},
		],
	},
	{
		name        : 'vessel_image_urls',
		label       : 'Vessel Image URLs',
		type        : 'fieldArray',
		placeholder : '',
		rules       : {},
		emptyValues : [
			{ image_url: undefined },
		],
		controls: [
			{
				name        : 'image_url',
				label       : 'Image URL',
				type        : 'fileUpload',
				placeholder : 'Image link',
				rules       : {},
			},
		],
	},
];
